try:
        print(x)        # x is not defined
except NameError:	# named error
        print("NameError")
except:                 # any error
        ("Error")
# else:			# optional
#       ("Nothing went wrong")

# finally:		# optional
#       f.close()
                        # runs at end of try..except